version: "3.3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "127.0.0.1:15672:15672"  
      - "127.0.0.1:5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
